name: Code-Linter

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  Code-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: "x64"
      - name: Check formatting with black
        uses: psf/black@stable
        with:
          options: "--check"
