# REF: https://github.com/okeeffed/hello-pytest-github-actions/blob/main/.github/workflows/pytest.yml
name: Tests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup/Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install test dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run Pytest
        run: |
          pytest -n 5 --cov --cov-config=.coveragerc tests/
